'use client';

import React from 'react';
import { PageLayout } from '../../../layouts/PageLayout';
import { Card, Skeleton } from '../../../components/ui/design-system';

export default function ReportsPage() {
  return (
    <PageLayout
      title="System Execution Reports"
      description="View, export, and download audits generated by workflow execution pipelines."
    >
      <div className="space-y-4">
        <Card className="p-6 space-y-4">
          <div className="flex justify-between items-center pb-3 border-b border-border/30">
            <h3 className="font-bold text-sm">Generated System Reports</h3>
            <span className="text-xs text-muted-foreground">0 items total</span>
          </div>
          <div className="space-y-3">
            <Skeleton className="h-10 w-full" />
            <Skeleton className="h-10 w-full" />
            <Skeleton className="h-10 w-full" />
          </div>
        </Card>
      </div>
    </PageLayout>
  );
}
